### PR TITLE
Pull request Version 3.0

### PR DESCRIPTION
**Pull request by bergstri**
CharacterFactory: 
-equipSurvivors: equips Survivors with weapons from the cache
-randomWeaponCache: generates a random weapon cache
-randomWeaponType: returns a random type of weapon (Pistol, Shotgun, FryingPan, etc.)

ZombieUniverstity: (main file)
-made CharacterFactory object to perform methods (randomSurvivorArray, equipSurvivors, randomZombieArray)
-equipped survivors with weapons so they have a greater fighting chance against the zombie hoard

Character:
-corrected formatting in kill feed that occurred when a zombie killed a survivor and it printed out the survivor's weapon.

Survivor:
-Was not able to get toString to work in the kill feed when printing out the weapons, so I opted to use instanceof to manually set the weapon names based on what the Survivor had equipped. This way the kill feed is implemented successfully as outlined in release 3.0.

### CODE REVIEW

**Comment by bergstri** [comment]
Daniel helped me out by giving me advice on how to best implement the methods given the code we have.

**Review by carterd4 — APPROVED** [review]
This looks good, if there was more time, I personally would have liked to see a more/better implementation of the objects being manipulated in the code, however, what was done with the code, was really good!
As this code was being culled into existence, the questions you asked were spot on!  The collaboration that happened to create this code was good!  Thanks Dan out

**Comment by bergstri** [comment]
If we all agree on this, I think this pull request should be our final revision on this project so we can keep studying for the exam! Thanks and good luck to everyone!

**Review by whitcompcsp — APPROVED** [review]
Good job!

**Pull request merged**
