### PR TITLE
Create weapons and handle holding weapons

### PR DESCRIPTION
**Pull request by whitcompcsp**
We'll need this for creating weapons.

### CODE REVIEW

**Comment by whitcompcsp** [comment]
I decided to go ahead and add more commits. This will handle these requirements:
- Indicates weapon used to kill an infected in kill feed
- Weapons can miss depending on accuracy. This is done by generating a random number between 0 and 99. If the accuracy is greater than the generated number, the weapon hits.
- Setting the weapon changes the damage of the character to the weapon's damage.

We don't have any weapons, so every survivor in the kill feed is going to say (Unarmed)

**Review by wpjeudy — COMMENTED** [review]
I can't believe you did all this in so little time!

I am not sure where I should place my ideas so I am going to place them here. Let me know if you would like me to place them elsewhere.


Submachine Gun - 55
Assault Rifle - 40
Shotgun - 33
Pistol – 23
Crossbow - 12
Axe – 10
Butcher Knife - 7
Crowbar - 4
Frying Pan - 1

**Comment by whitcompcsp** [comment]
@wpjeudy We might want to make sure they do at least as much damage as the strongest Survivor unit's unarmed damage. That way we don't end up with a weaker survivor because they decided to pick up a weapon.

Here's how I'd balance them, personally:
- I'd make the axe and shotgun the most powerful but least accurate.
   - The axe is big and heavy, and it's probably going to slice a common zombie in half in one hit, but its heaviness also makes it unreliable and hard to hit with.
    - The shotgun can be made a bit more accurate than an axe while being a bit less powerful. 

- I'd make the crowbar and assault rifles the most accurate but least powerful.
    - The crowbar doesn't weigh that much and should be easy to handle. 100% accuracy probably isn't out of the question for it.
    - The assault rifle should be a bit more powerful than a crowbar but less accurate because it's projectile-based.

- I'd make the middle three weapons (pistol, frying pan, submachine gun) well... in the middle.
    - The submachine gun can be more powerful but less accurate than a pistol. It's a rapid fire weapon, so you do a lot of damage, but it's not that accurate.
    - The pistol can be right in the middle. Decent damage and reliable, but nothing more.
    - The frying pan can do less damage than a pistol but be more accurate.

**Comment by bergstri** [comment]
We appreciate all the work you have done. This project needs to be clear, concise, and to the point. We should take a look at the code we have so far and see if it reflects these values. We have an obligation to make it as clear and concise as possible. 
Dan and I are going to take a look and try to rework some of the code this afternoon.

**Review by bergstri — APPROVED** [review]

**Review by carterd4 — APPROVED** [review]
Thank you for all the hard work that you have already contributed! We as a group agreed to keep this project as clear and concise as possible, so we should be able to merge or reshape some of this code so that we can simplify, Ian and I will take a look at this code and try to reshape it with that intent. Again great job making all this happen.

**Comment by wpjeudy** [comment]
> @wpjeudy We might want to make sure they do at least as much damage as the strongest Survivor unit's unarmed damage. That way we don't end up with a weaker survivor because they decided to pick up a weapon.
> 
> Here's how I'd balance them, personally:
> 
> * I'd make the axe and shotgun the most powerful but least accurate.
>   
>   * The axe is big and heavy, and it's probably going to slice a common zombie in half in one hit, but its heaviness also makes it unreliable and hard to hit with.
>   * The shotgun can be made a bit more accurate than an axe while being a bit less powerful.
> * I'd make the crowbar and assault rifles the most accurate but least powerful.
>   
>   * The crowbar doesn't weigh that much and should be easy to handle. 100% accuracy probably isn't out of the question for it.
>   * The assault rifle should be a bit more powerful than a crowbar but less accurate because it's projectile-based.
> * I'd make the middle three weapons (pistol, frying pan, submachine gun) well... in the middle.
>   
>   * The submachine gun can be more powerful but less accurate than a pistol. It's a rapid fire weapon, so you do a lot of damage, but it's not that accurate.
>   * The pistol can be right in the middle. Decent damage and reliable, but nothing more.
>   * The frying pan can do less damage than a pistol but be more accurate.

Sorry, I did not realize you wanted me to work on accuracy too.

I have made some modifications based on what Paul said.

Numbers ( Damage / Range of accuracy)

**Strongest**:
Axe - 74 / 40-65%
ShotGun - 70 / 43-75%

**Middle-range**:
SubmachineGun - 59 / 50-68%
Crossbow - 55 / 48-60%
Pistol - 50 / 45-55%
ButtherKnife - 45 / 60-72%
FryingPan - 39 / 75-95%

**Weakest**:
AssultRiffle - 30 / 70 - 92%
Crossbar - 24 / 90-100%

**Comment by wpjeudy** [comment]
> Thank you for all the hard work that you have already contributed! We as a group agreed to keep this project as clear and concise as possible, so we should be able to merge or reshape some of this code so that we can simplify, Ian and I will take a look at this code and try to reshape it with that intent. Again great job making all this happen.

I am ok with you using whichever one I posted. I think the Damage for the new posts might better align with what Paul has in mind, even if we don't use the accuracy.  Sorry for miss understanding!

**Comment by bergstri** [comment]
Thanks, Patricia! I just started with the Crowbar and will implement these changes you have outlined above. Dan and I should have this done by later tonight and we will keep the team posted with our progress.

**Pull request merged**
